package com.vcam.baker

import java.io.File
import java.util.Locale

data class CubeLut(val size: Int, val data: FloatArray)

object LutBaker {
    const val LUT_SIZE = 33

    fun bake(params: FilterParams): CubeLut {
        val n = LUT_SIZE
        val data = FloatArray(n * n * n * 3)
        var i = 0
        for (b in 0 until n) {
            for (g in 0 until n) {
                for (r in 0 until n) {
                    val input = Rgb(r.toFloat() / (n - 1), g.toFloat() / (n - 1), b.toFloat() / (n - 1))
                    val out = ColorPipeline.apply(input, params)
                    data[i++] = out.r
                    data[i++] = out.g
                    data[i++] = out.b
                }
            }
        }
        return CubeLut(n, data)
    }

    fun writeCubeFile(filterId: String, lut: CubeLut, out: File) {
        out.parentFile?.mkdirs()
        out.bufferedWriter().use { w ->
            w.appendLine("# V-Cam procedural LUT — $filterId")
            w.appendLine("# Generated by LutBaker. Do not edit by hand.")
            w.appendLine("TITLE \"V-Cam $filterId\"")
            w.appendLine("LUT_3D_SIZE ${lut.size}")
            w.appendLine("DOMAIN_MIN 0.0 0.0 0.0")
            w.appendLine("DOMAIN_MAX 1.0 1.0 1.0")
            val n = lut.size
            for (b in 0 until n) {
                for (g in 0 until n) {
                    for (r in 0 until n) {
                        val idx = ((b * n + g) * n + r) * 3
                        w.append(String.format(Locale.US, "%.6f %.6f %.6f%n", lut.data[idx], lut.data[idx + 1], lut.data[idx + 2]))
                    }
                }
            }
        }
    }
}
